# Generated by Django 4.2.3 on 2023-07-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sename', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='hall',
            new_name='hell',
        ),
    ]
