# Generated by Django 4.2.3 on 2023-07-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sename', '0002_rename_hall_movie_hell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='hell',
            new_name='hall',
        ),
    ]
